### ISSUE TITLE
Backslashes get rendered in black

### ISSUE THREAD

**Issue by harshbhatt** [framer/syntax-atom-ui#5]
Backslashes get rendered in black and become practically invisible against dark background (tested on a .c file and .lua file)

<img width="140" alt="image" src="https://user-images.githubusercontent.com/8042576/51575845-abd7f600-1e68-11e9-8895-014111307e90.png">

**Comment by alenart91** [comment]
I'm having the same issue, none of the files seem to target that particular syntax so I can't change the color.
